branch-defaults:
  clarify-directory-readme:
    environment: blog-qa
    group_suffix: null
global:
  application_name: sample_phoenix
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  profile: null
  sc: git
